// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCD.Services.ProductAPI.Data;

#nullable disable

namespace SCD.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SCD.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Category = "Clothing",
                            Description = "Nice t-shirt",
                            ImageUrl = "/images/110040ba-d84e-48bc-b12a-3953a8c147b4.png",
                            Name = "T-shirt",
                            Price = 499.0
                        },
                        new
                        {
                            ID = 2,
                            Category = "Clothing",
                            Description = "Chipest jeans",
                            ImageUrl = "/images/404d8e91-5765-4ae6-ae8d-5f9f9c4d087e.png",
                            Name = "Jeans",
                            Price = 1199.0
                        },
                        new
                        {
                            ID = 3,
                            Category = "Clothing",
                            Description = "Stylist jacket",
                            ImageUrl = "/images/872eb7f6-3f47-46b1-baa1-96e3bf567b78.png",
                            Name = "Jacket",
                            Price = 1499.0
                        },
                        new
                        {
                            ID = 4,
                            Category = "Footwear",
                            Description = "Cool shoes",
                            ImageUrl = "/images/e1e83066-802d-40b8-bdbc-dacbc63a848b.png",
                            Name = "Shoes",
                            Price = 1999.0
                        },
                        new
                        {
                            ID = 5,
                            Category = "Footwear",
                            Description = "Princes style",
                            ImageUrl = "/images/98bb4ebf-3794-4a3e-a2d0-4ef4e0380f9a.png",
                            Name = "Sandals",
                            Price = 799.0
                        },
                        new
                        {
                            ID = 6,
                            Category = "Accessories",
                            Description = "Looks rocking ",
                            ImageUrl = "/images/cbee0ecf-19dc-400a-892f-35122d43b00f.png",
                            Name = "Cap",
                            Price = 299.0
                        },
                        new
                        {
                            ID = 7,
                            Category = "Accessories",
                            Description = "Awesome watch",
                            ImageUrl = "/images/bed1a22a-4147-4546-8aab-06301a3df2cd.png",
                            Name = "Watch",
                            Price = 1599.0
                        },
                        new
                        {
                            ID = 8,
                            Category = "Accessories",
                            Description = "Compact bag",
                            ImageUrl = "/images/3202cac7-8d3c-4d93-8235-a6fd7f1a85ed.png",
                            Name = "Laptop Bag",
                            Price = 899.0
                        },
                        new
                        {
                            ID = 9,
                            Category = "Electronics",
                            Description = "High base",
                            ImageUrl = "/images/b4c2f781-04f3-4add-aabf-89943f03ee07.png",
                            Name = "Headphones",
                            Price = 2499.0
                        },
                        new
                        {
                            ID = 10,
                            Category = "Electronics",
                            Description = "Huge features",
                            ImageUrl = "/images/b3cddf57-7051-43b5-b8f7-915f9913b30e.png",
                            Name = "Laptop",
                            Price = 15999.0
                        },
                        new
                        {
                            ID = 11,
                            Category = "Footwear",
                            Description = "Cool lofer",
                            ImageUrl = "/images/b3cddf57-7051-43b5-b8f7-915f9913b30e.png",
                            Name = "Lofer",
                            Price = 15999.0
                        },
                        new
                        {
                            ID = 12,
                            Category = "Electronics",
                            Description = "Smart induction",
                            ImageUrl = "/images/442ad0e3-ddd2-474d-8877-660bc7114f0f.png",
                            Name = "Induction",
                            Price = 15999.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
