# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build AZ Function App - SCD-AS-EmailProcessorFunc

on:
  push:
    branches:
      - main
    paths:
      - 'ShoppingCartDemo/SCD.EmailProcessorFunction/**' 
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build "ShoppingCartDemo/SCD.EmailProcessorFunction/SCD.EmailProcessorFunction.csproj" --configuration Release --output ./output
          popd
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F5A5BF3D73284993B79539610EB39E02 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_52E22FD816A04F70B19A53FF7B5A8B2D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_20503FEC40A1442DAD4AD275997D41D0 }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'SCD-AS-EmailProcessorFunc'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

  SyncCode:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Repository
      uses: actions/checkout@v3
        
    - name: Set up Git
      run: |
        git config --global user.name "rajeevsharma4nagarro"
        git config --global user.email "rajeev.sharma@nagarro.com"

    - name: Clone Azure DevOps Repository
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        AZURE_DEVOPS_REPO_URL: ${{ secrets.AZURE_DEVOPS_REPO_URL }}Repo_SCD_EmailProcessorFunction
      run: |
        git clone https://:${AZURE_DEVOPS_PAT}@${AZURE_DEVOPS_REPO_URL#https://} email-processor-repo
                  
    - name: Copy GitHub repo contents to Azure Repo folder
      run: |
        rsync -av --delete --exclude='.git' ShoppingCartDemo/SCD.EmailProcessorFunction/ email-processor-repo/
        
    - name: Commit and Push to Azure DevOps
      run: |
        cd email-processor-repo
        git add .
        git commit -m "Sync from GitHub $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push origin main           


