# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build ASP.Net Core app - SCD-AS-Cart

on:
  push:
    branches:
      - main
    paths:
      - 'ShoppingCartDemo/SCD.Services.CartAPI/**'   
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore Dependencies
        run: dotnet restore "ShoppingCartDemo/SCD.Services.CartAPI/SCD.Services.CartAPI.csproj"
  
      - name: Build with dotnet
        run: dotnet build "ShoppingCartDemo/SCD.Services.CartAPI/SCD.Services.CartAPI.csproj" --configuration Release

      - name: dotnet publish
        run: dotnet publish "ShoppingCartDemo/SCD.Services.CartAPI/SCD.Services.CartAPI.csproj" -c Release -o "${{env.DOTNET_ROOT}}/SCD-AS-Cart"
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/SCD-AS-Cart

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_71F69CCADC794A32867FA8E3A9FBB057 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A960EC6DD19D4714AE35568CB1D86DDD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_62742017759841ED8C99E20C968DC8CF }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SCD-AS-Cart'
          slot-name: 'Production'
          package: .

  SyncCode:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Repository
      uses: actions/checkout@v3
        
    - name: Set up Git
      run: |
        git config --global user.name "rajeevsharma4nagarro"
        git config --global user.email "rajeev.sharma@nagarro.com"

    - name: Clone Azure DevOps Repository
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        AZURE_DEVOPS_REPO_URL: ${{ secrets.AZURE_DEVOPS_REPO_URL }}Repo_SCD_CartAPI
      run: |
        git clone https://:${AZURE_DEVOPS_PAT}@${AZURE_DEVOPS_REPO_URL#https://} cart-repo
                  
    - name: Copy GitHub repo contents to Azure Repo folder
      run: |
        rsync -av --delete --exclude='.git' ShoppingCartDemo/SCD.Services.CartAPI/ cart-repo/
        
    - name: Commit and Push to Azure DevOps
      run: |
        cd cart-repo
        git add .
        git commit -m "Sync from GitHub $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push origin main          

