# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Angular UI to Azure Web App - uiapp

on:
  push:
    branches:
      - main
    paths:
      - 'ShoppingCartDemo/SCD_UI/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build Angular app
        working-directory: ShoppingCartDemo/SCD_UI
        run: |
          npm install
          npm run build

      - name: Upload Angular build output
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: ShoppingCartDemo/SCD_UI/dist/SCD_UI/browser/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  # Required for Azure login
      contents: read

    steps:
      - name: Download Angular build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-build
          path: deploy-folder  # Custom folder to avoid root-level clutter

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9BB962C3250D45A88FB6075B231357FA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_87300D1CDDF249169786D3B320DB1E1F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_39010C1FE99D4A04847951281CFCDB16 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'uiapp'  # Replace with your actual Azure Web App name
          slot-name: 'Production'
          package: deploy-folder  # This must point to the downloaded artifact folder

